# File to generate HTML from AI-generated product data
import json
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

# --- Paths ---
DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "ai_generated_products.json"
TEMPLATE_PATH = Path(__file__).resolve().parent / "templates"
EXPORT_DIR = Path(__file__).resolve().parent

# --- Create export directory if it doesn't exist ---
EXPORT_DIR.mkdir(exist_ok=True)

# --- Load data ---
with open(DATA_PATH, "r") as f:
    products = json.load(f)

# --- Setup Jinja2 environment ---
environment = Environment(loader=FileSystemLoader(TEMPLATE_PATH))
template = environment.get_template("product_template.html")

# --- Generate HTML files ---
for product in products:
    product_name = product["product_name"].replace(" ", "_").lower()
    output_path = EXPORT_DIR / f"{product_name}.html"

    html_content = template.render(
        meta_title=product["meta_title"],
        meta_description=product["meta_description"],
        product_name=product["product_name"],
        product_description=product["product_description"]
    )

    with open(output_path, "w") as f:
        f.write(html_content)

    print(f"✅ Generated HTML for {product['product_name']} → {output_path}")

print("\n🎉 All pages generated successfully in /html_export!")

# --- Create an index page linking to all product pages ---
index_template = """
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SEO Product Index</title>
    <style>
      body {
        font-family: system-ui, sans-serif;
        max-width: 700px;
        margin: 2rem auto;
        padding: 1rem;
        color: #333;
      }
      h1 {
        text-align: center;
        margin-bottom: 2rem;
      }
      ul {
        list-style-type: none;
        padding: 0;
      }
      li {
        margin-bottom: 0.75rem;
      }
      a {
        text-decoration: none;
        color: #007bff;
      }
      a:hover {
        text-decoration: underline;
      }
      footer {
        margin-top: 3rem;
        font-size: 0.9rem;
        color: #888;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>SEO Product Index</h1>
    <p style="text-align:center;color:#555;">
        Explore automatically generated SEO pages for tech products.  
        Each page was created by a LangChain-powered AI pipeline that transforms structured data into optimized web content.
    </p>
    <ul>
      {% for product in products %}
      <li><a href="{{ product.filename }}">{{ product.name }}</a></li>
      {% endfor %}
    </ul>
    <footer>Generated by your A2 Mini Pipeline 🚀</footer>
  </body>
</html>
"""

# Prepare data for index page
index_data = [
    {
        "name": product["product_name"],
        "filename": f"{product['product_name'].replace(' ', '_').lower()}.html"
    }
    for product in products
]

# Render and save index.html
index_env = Environment()
index_html = index_env.from_string(index_template).render(products=index_data)
index_path = EXPORT_DIR / "index.html"

with open(index_path, "w") as f:
    f.write(index_html)

print(f"📄 Generated index page → {index_path}")
print("\n🎉 All pages (and index) generated successfully in /html_export!")